<a href="https://colab.research.google.com/github/SashankChintapalli/Food-Waste-Management-Project/blob/main/Emission_in_Food_Transport.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Wrangling Emissions Dataset**
FAO - Food and Agriculture Organization of the United Nations, is a specialized agency of the United Nations that leads international efforts to defeat hunger.
[Database here](https://www.fao.org/faostat/en/#data/GT)

In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('/content/Food_Data.csv')

In [7]:
df

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Source Code,Source,Unit,Value,Flag,Flag Description,Note
0,GT,Emissions totals,4,Afghanistan,7225,Emissions (CH4),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,0.0149,E,Estimated value,NaN
1,GT,Emissions totals,4,Afghanistan,7230,Emissions (N2O),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,0.0056,E,Estimated value,NaN
2,GT,Emissions totals,4,Afghanistan,7273,Emissions (CO2),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,61.2226,E,Estimated value,NaN
3,GT,Emissions totals,4,Afghanistan,724413,Emissions (CO2eq) from CH4 (AR5),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,0.4168,E,Estimated value,NaN
4,GT,Emissions totals,4,Afghanistan,724313,Emissions (CO2eq) from N2O (AR5),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,1.4758,E,Estimated value,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45496,GT,Emissions totals,716,Zimbabwe,7230,Emissions (N2O),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,0.0246,E,Estimated value,NaN
45497,GT,Emissions totals,716,Zimbabwe,7273,Emissions (CO2),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,257.9658,E,Estimated value,NaN
45498,GT,Emissions totals,716,Zimbabwe,724413,Emissions (CO2eq) from CH4 (AR5),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,1.2150,E,Estimated value,NaN
45499,GT,Emissions totals,716,Zimbabwe,724313,Emissions (CO2eq) from N2O (AR5),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,6.5209,E,Estimated value,NaN
45500,GT,Emissions totals,716,Zimbabwe,723113,Emissions (CO2eq) (AR5),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,265.7017,E,Estimated value,NaN

In [8]:
df.columns = df.columns.str.lower()

In [9]:
df.columns = df.columns.str.replace(' ', '_')

In [10]:
df_filtered = df
df_filtered = df_filtered.rename(columns = {'area': 'country'})
df_filtered

,domain_code,domain,area_code_(m49),country,element_code,element,item_code,item,year_code,year,source_code,source,unit,value,flag,flag_description,note
0,GT,Emissions totals,4,Afghanistan,7225,Emissions (CH4),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,0.0149,E,Estimated value,NaN
1,GT,Emissions totals,4,Afghanistan,7230,Emissions (N2O),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,0.0056,E,Estimated value,NaN
2,GT,Emissions totals,4,Afghanistan,7273,Emissions (CO2),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,61.2226,E,Estimated value,NaN
3,GT,Emissions totals,4,Afghanistan,724413,Emissions (CO2eq) from CH4 (AR5),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,0.4168,E,Estimated value,NaN
4,GT,Emissions totals,4,Afghanistan,724313,Emissions (CO2eq) from N2O (AR5),6815,Food Transport,1990,1990,3050,FAO TIER 1,kt,1.4758,E,Estimated value,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45496,GT,Emissions totals,716,Zimbabwe,7230,Emissions (N2O),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,0.0246,E,Estimated value,NaN
45497,GT,Emissions totals,716,Zimbabwe,7273,Emissions (CO2),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,257.9658,E,Estimated value,NaN
45498,GT,Emissions totals,716,Zimbabwe,724413,Emissions (CO2eq) from CH4 (AR5),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,1.2150,E,Estimated value,NaN
45499,GT,Emissions totals,716,Zimbabwe,724313,Emissions (CO2eq) from N2O (AR5),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,6.5209,E,Estimated value,NaN
45500,GT,Emissions totals,716,Zimbabwe,723113,Emissions (CO2eq) (AR5),6815,Food Transport,2022,2022,3050,FAO TIER 1,kt,265.7017,E,Estimated value,NaN

In [11]:
df_filtered = df_filtered.drop(['domain', 'domain_code', 'element_code', 'item_code', 'year_code', 'source_code', 'source', 'flag', 'note', 'flag_description'], axis=1)

In [12]:
df_filtered["value"] = df_filtered["value"].round(2)
df_filtered

,area_code_(m49),country,element,item,year,unit,value
0,4,Afghanistan,Emissions (CH4),Food Transport,1990,kt,0.01
1,4,Afghanistan,Emissions (N2O),Food Transport,1990,kt,0.01
2,4,Afghanistan,Emissions (CO2),Food Transport,1990,kt,61.22
3,4,Afghanistan,Emissions (CO2eq) from CH4 (AR5),Food Transport,1990,kt,0.42
4,4,Afghanistan,Emissions (CO2eq) from N2O (AR5),Food Transport,1990,kt,1.48
...,...,...,...,...,...,...,...
45496,716,Zimbabwe,Emissions (N2O),Food Transport,2022,kt,0.02
45497,716,Zimbabwe,Emissions (CO2),Food Transport,2022,kt,257.97
45498,716,Zimbabwe,Emissions (CO2eq) from CH4 (AR5),Food Transport,2022,kt,1.22
45499,716,Zimbabwe,Emissions (CO2eq) from N2O (AR5),Food Transport,2022,kt,6.52
45500,716,Zimbabwe,Emissions (CO2eq) (AR5),Food Transport,2022,kt,265.70

In [13]:
list_countries = ['Angola', 'Argentina', 'Armenia', 'Australia', 'Azerbaijan',
       'Bangladesh', 'Benin', 'Bolivia (Plurinational State of)',
       'Botswana', 'Brazil', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Chad', 'Chile', 'China', 'Colombia',
       'Costa Rica', 'Cuba', "Côte d'Ivoire",
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Ecuador', 'Egypt',
       'El Salvador', 'Eritrea', 'Eswatini', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Ghana', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'India',
       'Indonesia', 'Iran (Islamic Republic of)', 'Italy', 'Jordan',
       'Kazakhstan', 'Kenya', "Lao People's Democratic Republic",
       'Lebanon', 'Lesotho', 'Liberia', 'Madagascar', 'Malawi',
       'Malaysia', 'Mali', 'Mauritania', 'Mexico', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Nicaragua', 'Niger',
       'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama',
       'Paraguay', 'Peru', 'Philippines', 'Republic of Korea', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia', 'Saudi Arabia', 'Senegal',
       'Sierra Leone', 'Somalia', 'South Sudan', 'Sri Lanka', 'Sudan',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Thailand',
       'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Uganda', 'Ukraine',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Zambia',
       'Zimbabwe']

In [14]:
df_filtered = df_filtered[df_filtered['country'].isin(list_countries)]
df_filtered.reset_index(drop=True, inplace=True)
df_filtered

,area_code_(m49),country,element,item,year,unit,value
0,24,Angola,Emissions (CH4),Food Transport,1990,kt,0.01
1,24,Angola,Emissions (N2O),Food Transport,1990,kt,0.01
2,24,Angola,Emissions (CO2),Food Transport,1990,kt,97.93
3,24,Angola,Emissions (CO2eq) from CH4 (AR5),Food Transport,1990,kt,0.35
4,24,Angola,Emissions (CO2eq) from N2O (AR5),Food Transport,1990,kt,1.76
...,...,...,...,...,...,...,...
20967,716,Zimbabwe,Emissions (N2O),Food Transport,2022,kt,0.02
20968,716,Zimbabwe,Emissions (CO2),Food Transport,2022,kt,257.97
20969,716,Zimbabwe,Emissions (CO2eq) from CH4 (AR5),Food Transport,2022,kt,1.22
20970,716,Zimbabwe,Emissions (CO2eq) from N2O (AR5),Food Transport,2022,kt,6.52
20971,716,Zimbabwe,Emissions (CO2eq) (AR5),Food Transport,2022,kt,265.70

In [15]:
df_filtered["element"].value_counts()

element
Emissions (CH4)                         3335
Emissions (N2O)                         3335
Emissions (CO2)                         3335
Emissions (CO2eq) from CH4 (AR5)        3335
Emissions (CO2eq) from N2O (AR5)        3335
Emissions (CO2eq) (AR5)                 3335
Emissions (CO2eq) from F-gases (AR5)     962
Name: count, dtype: int64

In [16]:
element_mapping = {
    'Direct emissions (N2O)': 'Nitrous Oxide (N2O)',
    'Emissions (N2O)': 'Nitrous Oxide (N2O)',
    'Emissions (CO2eq) from N2O (AR5)': 'Carbon Dioxide (CO2)',
    'Emissions (CO2eq) (AR5)': 'Carbon Dioxide (CO2)',
    'Emissions (CH4)': 'Methane (CH4)',
    'Emissions (CO2eq) from CH4 (AR5)': 'Carbon Dioxide (CO2)',
    'Emissions (CO2)': 'Carbon Dioxide (CO2)',
    'Emissions (CO2eq) from F-gases (AR5)': 'Carbon Dioxide (CO2)'
}
df_filtered["element"] = df_filtered["element"].replace(element_mapping)

<ipython-input-16-d9238102e8f5>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["element"] = df_filtered["element"].replace(element_mapping)

In [17]:
df_filtered

,area_code_(m49),country,element,item,year,unit,value
0,24,Angola,Methane (CH4),Food Transport,1990,kt,0.01
1,24,Angola,Nitrous Oxide (N2O),Food Transport,1990,kt,0.01
2,24,Angola,Carbon Dioxide (CO2),Food Transport,1990,kt,97.93
3,24,Angola,Carbon Dioxide (CO2),Food Transport,1990,kt,0.35
4,24,Angola,Carbon Dioxide (CO2),Food Transport,1990,kt,1.76
...,...,...,...,...,...,...,...
20967,716,Zimbabwe,Nitrous Oxide (N2O),Food Transport,2022,kt,0.02
20968,716,Zimbabwe,Carbon Dioxide (CO2),Food Transport,2022,kt,257.97
20969,716,Zimbabwe,Carbon Dioxide (CO2),Food Transport,2022,kt,1.22
20970,716,Zimbabwe,Carbon Dioxide (CO2),Food Transport,2022,kt,6.52
20971,716,Zimbabwe,Carbon Dioxide (CO2),Food Transport,2022,kt,265.70

In [18]:
df_filtered = df_filtered.groupby(['country', 'year', 'element', 'item', 'unit']).agg({'value':'mean'}).reset_index().round(2)

In [19]:
df_filtered

        country  year               element            item unit   value
0        Angola  1990  Carbon Dioxide (CO2)  Food Transport   kt   50.02
1        Angola  1990         Methane (CH4)  Food Transport   kt    0.01
2        Angola  1990   Nitrous Oxide (N2O)  Food Transport   kt    0.01
3        Angola  1991  Carbon Dioxide (CO2)  Food Transport   kt   49.32
4        Angola  1991         Methane (CH4)  Food Transport   kt    0.01
...         ...   ...                   ...             ...  ...     ...
10000  Zimbabwe  2021         Methane (CH4)  Food Transport   kt    0.04
10001  Zimbabwe  2021   Nitrous Oxide (N2O)  Food Transport   kt    0.02
10002  Zimbabwe  2022  Carbon Dioxide (CO2)  Food Transport   kt  132.85
10003  Zimbabwe  2022         Methane (CH4)  Food Transport   kt    0.04
10004  Zimbabwe  2022   Nitrous Oxide (N2O)  Food Transport   kt    0.02

[10005 rows x 6 columns]

In [20]:
df_filtered.to_csv('/content/Food_Data_updated.csv', index=False)